name: Code quality assessment
on: 
  pull_request:
    branches: 
      - main

jobs:
  BLACK:
    name: Run black module
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: |
          black --check --verbose .

  PYLINT:
    name: Lint Djagno project
    if: ${{ always() }}
    needs: [BLACK]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: |
          shopt -s globstar && pylint --load-plugins pylint_django --fail-under=8.0 --django-settings-module=SensorNet.settings **/*.py
  
